### ISSUE TITLE
Add support for Android Digital Asset Link validation

### ISSUE THREAD

**Issue by chayev** [chayev/yurl#45]

**Comment by FelicianoTech** [comment]
Is there a timeline for this? Or an alternative you suggest?

**Comment by chayev** [comment]
No current timeline but this is a high priority.

In the meantime you have a few options for alternatives:

-[Google's validator](https://developers.google.com/digital-asset-links/tools/generator) 
-[AppsFlyer's Validator](https://www.appsflyer.com/tools/link-validator/)

Note that I'm not sure how well both validators work, but they are available to try.

**Comment by FelicianoTech** [comment]
🎉
