### ISSUE TITLE
Bug: Incorrectly reports android deeplinks as invalid if contains anything other than application/json in the header

### ISSUE THREAD

**Issue by aceslick911** [chayev/yurl#79]
Services such as app.link return content-type headers: `application/json; charset=utf-8` and work fine with ios and android.
Android yURL results currently wrongly state this is invalid.

**Comment by aceslick911** [comment]
Fix: https://github.com/chayev/yurl/pull/80

**Comment by chayev** [comment]
@aceslick911 do you have examples of a few domains where the content type is `application/json; charset=utf-8`? 

For context - I based the validator on the spec [defined by Android](https://developer.android.com/training/app-links/verify-android-applinks#publish-json). It specifically says the content type should be `application/json`.

I'm open to the edit you suggested as I know that `application/json; charset=utf-8` works as well. I just want some examples to validate against before making the call.

**Comment by chayev** [comment]
@aceslick911 let me know if you have any examples

**Comment by chayev** [comment]
Closing due to lack of response
